version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: flaskApp
            MONGO_INITDB_ROOT_PASSWORD: qwerty123
            MONGO_INITDB_DATABASE: admin
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks:
            - ftt-network

    flask_app:
        build:
            context: .
        container_name: flask_app
        ports: 
            - 8080:8080
        restart: always
        environment:
            MONGODB_URI: mongodb://mongodb.ftt-network:27017 
        networks:
            - ftt-network
        depends_on: 
            - mongodb

networks:
    ftt-network:
        name: ftt-network
        driver: bridge
